package config

// registry_help.go holds per-parameter tuning guidance (Chinese).
// Each string explains what the parameter does, its default, and how to
// adjust it. Surfaced in the web UI via the "参数说明" panel and field
// tooltips (GET /api/params). Values mirror llama.cpp common/arg.cpp.

var paramHelp = map[string]string{
	// ── 📁 基础设置 ─────────────────────────────────────────
	"model":        "模型 GGUF 文件路径（必填）。由左侧模型库选择自动填入，也可手动指定。",
	"host":         "监听地址。默认 127.0.0.1 仅本机可访问；改成 0.0.0.0 可让局域网/其他程序调用（务必配合设置 API Key）。",
	"port":         "服务端口（1-65535）。启动多个实例时请用不同端口。默认 8080。",
	"api_key":      "OpenAI 兼容 API 的访问密钥。设置后调用 /v1/* 接口需在请求头带 `Authorization: Bearer <key>`。留空=不校验。推荐在 ⚙️设置 里配置全局 Key（AES-256 加密存储），此处可临时覆盖。",
	"api_key_file": "从文件读取 API Key（明文文件，替代在命令行传 Key，更安全）。与 api_key 二选一。",

	// ── ⚡ 性能调优 ─────────────────────────────────────────
	"n_gpu_layers":  "卸载到 GPU 的层数。0=纯 CPU；-1=自动；-2 及以上=全部。显存充足时加大可显著提速，显存不足会 OOM——可配合“一键优化”自动估算。",
	"device":        "参与计算的 GPU 设备（如 0、1）。多卡时可指定多块。",
	"main_gpu":      "主 GPU 编号，负责小张量与临时缓冲（默认 0）。",
	"split_mode":    "多卡张量拆分方式：none=不拆分、layer=按层、row=按行、tensor=按张量。多卡推理常用 layer。",
	"tensor_split":  "手动指定各 GPU 的权重分配比例，逗号分隔（如 0.5,0.5）。一般用 split-mode 即可，无需手动设置。",
	"fit":           "自动适配显存：启动时按空闲显存自动调整上下文/层数等。开启后配合 fit-target/fit-ctx。",
	"threads":       "计算线程数。0=自动（CPU 核心数）。CPU 推理可手动调大，但超过物理核数反而变慢。",
	"threads_batch": "批处理阶段线程数。0=跟随 threads。调大可加速长 prompt 的首 token 生成。",
	"ctx_size":      "上下文长度（token）。越大占用显存/内存越多。默认 4096；长对话或长文档可加大（如 8192/16384）。",
	"batch_size":    "逻辑批大小。默认 2048。GPU 推理通常保持默认即可。",
	"ubatch_size":   "物理批大小（默认 512）。一般无需改动。",
	"flash_attn":    "Flash Attention 加速：on=强制开、off=关闭、auto=自动。开启可省显存并提速；量化 KV 缓存（非 f16）强烈建议保持 on。",
	"cache_type_k":  "K 缓存数据类型。f32/f16/bf16=浮点（精度高）；q8_0/q4_0/q4_1/iq4_nl/q5_0/q5_1=量化（省显存，精度略降）。量化后建议开启 Flash Attention。默认 f16。",
	"cache_type_v":  "V 缓存数据类型，同 K 缓存。通常与 cache-type-k 保持一致。",
	"cpu_moe":       "MoE 模型的专家层驻留 CPU，节省显存（速度略降）。MoE 模型显存紧张时建议开启。",
	"n_cpu_moe":     "指定驻留 CPU 的 MoE 专家层数（0=自动/不指定）。",
	"fit_target":    "每块设备预留的空闲显存余量（如 1024MiB），配合 --fit 使用。",
	"fit_ctx":       "--fit 模式下允许缩减到的最小上下文（0=不限制）。",
	"check_tensors": "启动时校验模型张量完整性，发现损坏时报错。排查模型文件是否损坏时开启。",
	"rope_scaling":  "RoPE 位置编码缩放方式：none=不缩放、linear=线性外推、yarn=YaRN（长上下文效果更好）。留空=自动（跟随模型元数据）。扩长上下文时优先选 yarn。",
	"rope_scale":    "RoPE 上下文缩放因子：填 N 表示把上下文扩展 N 倍（如 2 = 2 倍）。留空=自动（不额外缩放）。与 rope-scaling 搭配使用，填 yarn 时此值即外推倍数。",
	"mmproj":        "多模态视觉投影文件（mmproj*.gguf）。留空=自动使用模型库中检测绑定的 mmproj；填写可手动覆盖为指定文件。",

	// ── 🧠 内存与加载 ───────────────────────────────────────
	"load_mode":           "模型加载模式。✅ 推荐：mmap（默认，启动快且省内存）。mlock=锁定到 RAM 防换页（模型被系统换出导致变慢时用，但会占满物理内存）；mmap+mlock=两者结合；dio=直接 IO；none=一次性读入（最慢）。内存特别紧张才考虑 none。",
	"kv_offload":          "KV 缓存卸载到 GPU，加速长上下文。✅ 推荐：显存充足时开启，显存紧张保持关闭（默认关闭）。",
	"repack":              "权重重打包：启动时重排低效数据类型以提升算力利用率。✅ 推荐：CUDA 卡开启（略增启动时间）；纯 CPU 推理可关闭。",
	"no_host":             "绕过主机缓冲区。✅ 推荐：保持关闭（默认），一般不需要开启。",
	"numa":                "NUMA 策略（多路 CPU 服务器用）。✅ 推荐：留空/自动（不设置，普通单路/消费级机器）；多路 CPU 服务器用 distribute 把层均匀分布到各节点。注意：新版 llama.cpp 不接受 none 值，留空即不启用。",
	"op_offload":          "把张量运算（如归一化）也卸载到设备。✅ 推荐：保持关闭（默认），一般不需要开启。",
	"cache_ram":           "提示缓存（prompt cache）最大内存，单位 MiB。✅ 推荐：保持默认 8192；内存紧张可调小（如 2048）；0=禁用缓存。跨请求复用已处理 prompt 时可加速重复输入。",
	"ctx_checkpoints":     "每个槽位最多创建的上下文检查点数（长文本/投机解码回滚用）。✅ 推荐：保持默认 32，一般不需要改。",
	"checkpoint_min_step": "上下文检查点之间的最小间隔（token 数）。✅ 推荐：保持默认 8192；值越小检查点越密、回滚越精确但更耗内存。",

	// ── 🔧 CPU 与调度 ───────────────────────────────────────
	"cpu_mask":        "CPU 亲和掩码（如 0x3 绑定前两个核）。追求低延迟时可绑定特定核。留空=不绑定。",
	"cpu_range":       "CPU 亲和范围（如 0-3 或 4,5）。与 cpu-mask 二选一，写法更直观。",
	"cpu_strict":      "严格 CPU 放置：未绑定范围内的线程报错而非降级。调试线程调度问题时用。",
	"prio":            "进程优先级（-1~3，越高越优先）。实时性要求高时调高。",
	"poll":            "忙轮询级别（0-100），降低调度延迟但更耗电。默认 50。",
	"cpu_mask_batch":  "批处理阶段的 CPU 掩码（与 threads-batch 对应）。",
	"cpu_range_batch": "批处理阶段的 CPU 范围。",
	"prio_batch":      "批处理阶段的进程优先级。",
	"poll_batch":      "批处理阶段的忙轮询级别。",

	// ── 🎨 生成控制 ─────────────────────────────────────────
	"samplers":           "采样器链：按分号分隔依次执行，格式 `sampler1;sampler2;...`。每个采样器按顺序过滤/调整候选 token，最终从剩余候选中随机挑一个。llama.cpp 默认：penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature。调整方法：①只保留你需要的采样器；②越靠前优先级越高；③不需要的可从链中删掉。",
	"sampler_seq":        "简化采样器序列（与采样器链二选一）：用单字符缩写描述采样顺序，如 `edskypmxt`（e=top-k、d=DRY、s=top-n-sigma、k=top-k、y=typ-p、p=top-p、m=min-p、x=XTC、t=温度）。填了它就不再需要写完整的采样器链。",
	"ignore_eos":         "忽略 EOS 结束符：模型不会因遇到结束 token 停止，会持续生成（等价于 --logit-bias EOS-inf）。用于强制长输出。",
	"temperature":        "温度（0-2）：越高输出越随机发散，越低越确定。创意写作可调 0.8-1.2；代码/事实类任务调 0.2-0.6。默认 0.8。",
	"top_k":              "Top-K：只从概率最高的前 K 个 token 中采样。40 是常用值；0=禁用（交给 top_p）。",
	"top_p":              "Top-P（核采样）：从累积概率达到 P 的最小 token 集合中采样。0.95 常见；越低越保守。",
	"min_p":              "Min-P：过滤掉概率低于“最高概率×P”的 token。0.05 常用；0=禁用。可与 top_k/top_p 叠加。",
	"seed":               "随机种子：-1=每次随机；固定整数=结果可复现。调参对比时固定 seed 便于对照。",
	"predict":            "最多生成多少 token。默认 -1=不限制（直到结束符/上下文满）。防止无限生成时设置上限。",
	"dry_multiplier":     "DRY 重复惩罚乘数（0=禁用）。惩罚重复序列，减少复读。配合 dry-base 使用。",
	"dry_base":           "DRY 惩罚基数（默认 1.75）。值越大对重复惩罚越强。",
	"dry_allowed_length": "DRY 允许的重复长度（默认 2）：低于此长度的重复不惩罚。",
	"dry_penalty_last_n": "DRY 回溯窗口（默认 -1=整个上下文）。只统计最近 N 个 token 的重复。",
	"xtc_probability":    "XTC 随机截断概率（0-1，0=禁用）：按概率移除概率最高的候选，强制探索次优 token，减少陈词滥调。",
	"xtc_threshold":      "XTC 截断阈值（默认 0.1）：候选概率低于此值才参与截断。",
	"top_nsigma":         "Top-N-Sigma（默认 -1=禁用）：按标准差阈值过滤尾部候选，兼顾质量与多样性。",
	"adaptive_target":    "Adaptive-P 目标熵（0-1，0=禁用）：动态调整 top_p 使输出熵接近目标。",
	"adaptive_decay":     "Adaptive-P 衰减系数（0=禁用）：控制 top_p 调整速度。",
	"typical":            "Locally Typical（1.0=禁用）：偏向“典型”的 token，抑制意外输出。",
	"dynatemp_range":     "动态温度范围（0=禁用）：在 [temp-range, temp+range] 间按困惑度波动。",
	"dynatemp_exp":       "动态温度指数（默认 1.0）：调整波动曲线的敏感度。",
	"mirostat":           "Mirostat 自适应采样（0=禁用、1/2=启用）：自动调整温度维持目标熵，输出更稳定。",
	"mirostat_lr":        "Mirostat 学习率（默认 0.1）：越大调节越快但越抖。",
	"mirostat_ent":       "Mirostat 目标熵（默认 5.0）：越低输出越保守。",
	"grammar":            "BNF 文法约束：把输出限制为指定语法格式（如 JSON、代码）。适合结构化输出。",
	"grammar_file":       "从 .gbnf 文件读取文法规则（与 grammar 二选一）。",
	"json_schema":        "JSON Schema 约束：直接贴 schema，让输出符合该 JSON 结构（比 grammar 更省事）。",
	"json_schema_file":   "从文件读取 JSON Schema（与 json_schema 二选一）。",

	// ── 🧩 投机解码 ─────────────────────────────────────────
	"spec_type":                 "投机解码类型：draft-simple=独立小草稿模型、draft-eagle3=EAGLE-3、draft-mtp=多 token 预测（主模型自带 MTP 头时直接用，如 Qwen3-MTP/Qwopus-MTP）、draft-dflash/draft-dspark=扩散式草稿、ngram-*=无模型 n-gram 草稿。用小模型或专用头预猜输出，大幅提速。",
	"model_draft":               "草稿模型路径（投机解码用）。选择一个小而快的模型。",
	"n_gpu_layers_draft":        "草稿模型卸载到 GPU 的层数（默认 0=全 CPU）。草稿模型小，可全放 GPU 加速。",
	"spec_draft_threads":        "草稿模型线程数（0=自动）。",
	"spec_draft_poll":           "草稿模型轮询模式（0/1，0=等待通知、1=轮询忙等）。CPU 草稿时偶尔能提速。",
	"spec_draft_cpu_mask_batch": "草稿模型批处理阶段的 CPU 亲和掩码（默认跟随草稿掩码）。",
	"spec_draft_prio_batch":     "草稿模型批处理阶段优先级（-1..3）。",
	"spec_draft_poll_batch":     "草稿模型批处理阶段轮询（0/1，默认跟随 --spec-draft-poll）。",
	"spec_draft_cpu_mask":       "草稿模型 CPU 亲和掩码。",
	"spec_draft_prio":           "草稿模型进程优先级（-1~3）。",
	"spec_draft_device":         "草稿模型使用的 GPU 设备。",
	"spec_draft_cache_type_k":   "草稿模型 K 缓存类型（默认 f16）。",
	"spec_draft_cache_type_v":   "草稿模型 V 缓存类型（默认 f16）。",
	"spec_draft_n_max":          "草稿最多预生成几个 token（默认 3）。越大加速越多但验证开销也大。",
	"spec_draft_n_min":          "草稿最少接受几个 token（默认 0）。",
	"spec_draft_p_split":        "分裂概率（默认 0.1）：把部分计算分给目标模型，减少草稿错误。",
	"spec_draft_p_min":          "草稿最小接受概率（默认 0）。",
	"spec_ngram_mod_n_min":      "ngram-mod 的 n 最小（默认 0）。",
	"spec_ngram_mod_n_max":      "ngram-mod 的 n 最大（默认 4）。",
	"spec_ngram_simple_size_n":  "ngram-simple 的 n-gram 长度（默认 4）。",
	"lookup_cache_static":       "静态查找缓存文件（lookup 解码用，生成时不更新）。配合 --spec-type ngram-cache。",
	"lookup_cache_dynamic":      "动态查找缓存文件（lookup 解码用，生成时持续更新）。配合 --spec-type ngram-cache。",
	"spec_ngram_simple_size_m":  "ngram-simple 的查询长度（默认 4）。",

	// ── 📥 模型来源 ─────────────────────────────────────────
	"hf_repo":     "从 HuggingFace 拉取模型：填仓库 ID（如 ggml-org/llama-3.2-1B-GGUF）。",
	"hf_file":     "HF 仓库内指定文件名（默认自动选最优量化）。",
	"hf_token":    "HF 访问令牌（私有/需授权仓库必填）。",
	"model_url":   "直接给模型下载 URL（HTTP 直链）。",
	"docker_repo": "Docker 镜像仓库（容器部署场景）。",
	"no_mmproj":   "禁用 mmproj 的自动下载（多模态场景不需要视觉时勾选）。",
	"offline":     "强制使用本地缓存，不联网。",

	// ── 🌐 网络与安全 ───────────────────────────────────────
	"ssl_key_file":  "HTTPS 私钥文件路径（配合 ssl-cert-file 启用 HTTPS）。",
	"ssl_cert_file": "HTTPS 证书文件路径。启用后服务走 HTTPS。",
	"cors_origins":  "允许的跨域来源（逗号分隔，如 https://app.example.com）。网页前端跨域调用时设置。",
	"cors_methods":  "允许的跨域方法（默认 GET,POST）。",
	"timeout":       "HTTP 读写超时秒数（默认 3600）。长生成任务可调大。",
	"threads_http":  "处理 HTTP 请求的线程数。-1=自动。并发请求多时调大可降低排队延迟；一般保持自动。",

	// ── 🧩 模板与推理 ───────────────────────────────────────
	"jinja":              "强制使用 Jinja 对话模板引擎（部分新模型需要）。默认自动。",
	"chat_template":      "对话模板（可自由填任意内置模板名）：llama2/llama3/llama4/qwen/chatml/mistral/chatglm3/chatglm4/deepseek/deepseek2/deepseek3/command-r/falcon3/gemma/granite-4.1/grok-2/hunyuan-vl/kimi-k2/exaone4/gpt-oss 等。留空=自动从模型元数据读取。模板不匹配会乱码/角色混乱。",
	"chat_template_file": "从文件加载自定义对话模板（Jinja2）。",
	"reasoning":          "思维链（推理）控制：on=强制开启、off=关闭、auto=跟随模型。推理模型建议 auto/on。",
	"reasoning_format":   "思维链输出格式：auto/thought/deepseek/qwen。默认 auto 跟随模型。",
	"reasoning_effort":   "推理努力级别（low/medium/high）：越高思考越久、答案越好但更慢。",
	"reasoning_budget":   "思维链 token 预算（0=不限制）。限制思考长度用。",

	// ── 📝 日志与调试 ───────────────────────────────────────
	"log_file":       "把日志写入文件（便于排查）。",
	"log_colors":     "日志着色：auto=自动（输出到终端才着色）、on=强制开、off=关闭。",
	"log_verbosity":  "日志详细度（默认 3）：0=常规、1=错误、2=警告、3=信息、4=跟踪、5=调试。排查问题时可临时调高。",
	"log_prefix":     "日志带来源前缀。",
	"log_timestamps": "日志带时间戳。",
	"log_disable":    "完全禁用日志输出。",
	"perf":           "输出内部性能计时（各阶段耗时）。调优时开启观察瓶颈。",

	// ── ⚡ 性能新增 ─────────────────────────────────────────
	"parallel":               "并行槽位（并发客户端数）。-1=自动（默认约 4 槽 + 统一 KV）。多客户端同时请求时设为需要的并发数。✅ 推荐：-1 自动。",
	"cont_batching":          "连续/动态批处理：请求到达即处理，无需等待整批。✅ 推荐：默认已启用，一般无需设置。",
	"slot_prompt_similarity": "slot 复用所需的提示词相似度阈值（0-1）。值越高越严格，相同前缀才能复用。默认 0.10。",
	"rope_freq_base":         "RoPE 基础频率（0=跟随模型）。调低可扩展长上下文，一般由模型决定。",
	"yarn_orig_ctx":          "YaRN 原始上下文长度（模型训练时的上下文，如 4096）。扩长上下文时填写。",
	"yarn_ext_factor":        "YaRN 外推混合因子（负值=跟随模型）。通常用 rope-scaling=yarn + 该值。",
	"yarn_attn_factor":       "YaRN 注意力幅度因子（负值=跟随模型）。",
	"yarn_beta_fast":         "YaRN 快速端校正维度（负值=跟随模型）。",
	"yarn_beta_slow":         "YaRN 慢速端校正维度（负值=跟随模型）。",
	"mmproj_url":             "多模态投影文件下载 URL（配合 -hf 自动下载 mmproj）。",
	"mmproj_device":          "mmproj 多模态模型使用的设备（auto=自动，或指定 GPU 编号）。",
	"no_mmproj_offload":      "让视觉投影（mmproj）在 CPU 上运行以节省显存，把显存让给主模型层（提升生成速度）。纯文本场景推荐勾选；纯多模态高频编码场景不建议。",
	"image_min_tokens":       "图像输入动态分辨率的最小 token 数（0=读模型默认）。Qwen-VL 等建议 ≥1024。",
	"image_max_tokens":       "图像输入动态分辨率的最大 token 数（0=读模型默认）。",
	"mtmd_batch_max_tokens":  "多模态图像编码的单批最大 token 数（默认 1024）。",
	"embedding":              "嵌入模式：加载专用嵌入模型后仅提供 /v1/embeddings（不生成文本）。RAG/检索场景用。",
	"pooling":                "嵌入池化方式：mean=平均、cls=首 token、last=末 token、rank=排序得分。留空=跟随模型。",
	"embd_normalize":         "嵌入向量归一化（-1=不归一化，0=最大绝对值 int16，1=taxicab，2=欧氏，>2=p-范数）。默认 2。",
	"rerank":                 "重排模式：启用 /v1/rerank 端点，用交叉编码器对文档重排。配 rerank 模型用。",
	"embd_output_format":     "嵌入输出格式（默认空=旧格式）：array=[[],[]...]、json=OpenAI 风格、json+=json+余弦相似度矩阵、raw=纯文本一行一个向量。",
	"embd_separator":         "嵌入向量分隔符（默认换行）。如 \"<#sep#>\"。",
	"cls_separator":          "分类序列分隔符（默认 Tab）。用于分类任务的序列切分。",

	// ── 🧠 内存新增 ─────────────────────────────────────────
	"keep":             "保留初始 prompt 的前 N 个 token 不被上下文截断丢弃（长对话保护关键指令）。默认 0。",
	"grp_attn_n":       "Grouped Attention 因子 n（0=模型默认）。配合 ctx-size 压长上下文内存。",
	"grp_attn_w":       "Grouped Attention 宽度 w（0=模型默认）。",
	"kv_unified":       "统一 KV 缓冲：所有 slot 共享一块 KV 缓存，省内存。auto slots 时默认开启。",
	"cache_idle_slots": "新任务时将空闲 slot 存入提示缓存并清空，需开启 cache-ram。默认启用。",
	"cache_reuse":      "通过 KV 移位复用提示缓存的最小块大小（0=禁用）。需开启提示缓存。",
	"cache_prompt":     "提示缓存开关（默认启用）。关闭可省内存但重复 prompt 会重复计算。",
	"context_shift":    "无限生成时上下文自动移位（超出 context 时丢弃旧 token）。长文本生成用。",
	"swa_full":         "使用全尺寸滑动窗口注意力（SWA）缓存，替代自动缩减。长上下文更稳但更耗内存。",
	"slot_save_path":   "槽位 KV 缓存保存目录（配合 /slots/{id}?action=save/restore API 实现会话持久化）。",

	// ── 🎨 采样新增 ─────────────────────────────────────────
	"repeat_penalty":    "重复惩罚（≥1）：对已出现 token 的概率打折，抑制复读。1.0=禁用；1.1-1.3 常用。",
	"repeat_last_n":     "重复惩罚回溯窗口：只看最近 N 个 token 的重复（默认 64）。",
	"presence_penalty":  "存在惩罚（-2~2）：对出现过的 token 一律减去固定值，鼓励引入新话题。0=禁用。",
	"frequency_penalty": "频率惩罚（-2~2）：按出现次数递减概率，抑制高频词。0=禁用。",
	"logit_bias":        "Logit 偏置：直接调整指定 token 的得分，格式 `ID(+/-)BIAS`（如 42+3.0），逗号分隔多个。",

	// ── 🧩 投机解码新增 ─────────────────────────────────────
	"spec_default":                "一键启用默认投机解码配置（自动选草稿方案）。快速上手用。",
	"spec_draft_backend_sampling": "把草稿模型采样卸载到后端加速（默认启用）。",
	"spec_draft_override_tensor":  "覆盖草稿模型张量缓冲类型，格式 `名称=类型,...`。高级调优。",
	"spec_draft_cpu_moe":          "草稿模型 MoE 专家层驻留 CPU，省显存。",
	"spec_draft_n_cpu_moe":        "草稿模型前 N 层 MoE 驻留 CPU（0=自动/不指定）。",
	"spec_draft_hf":               "草稿模型 HuggingFace 仓库 ID（自动下载草稿权重）。",
	"spec_ngram_mod_n_match":      "ngram-mod 查表匹配长度（默认 24）。",
	"spec_ngram_simple_min_hits":  "ngram-simple 最少命中次数才作为草稿（默认 1）。",
	"spec_ngram_map_k_size_n":     "ngram-map-k 的键 n-gram 长度（默认 12）。",
	"spec_ngram_map_k_size_m":     "ngram-map-k 的值 m-gram 长度（默认 48）。",
	"spec_ngram_map_k_min_hits":   "ngram-map-k 最少命中次数（默认 1）。",
	"spec_ngram_map_k4v_size_n":   "ngram-map-k4v 的键 n-gram 长度（默认 12）。",
	"spec_ngram_map_k4v_size_m":   "ngram-map-k4v 的值 m-gram 长度（默认 48）。",
	"spec_ngram_map_k4v_min_hits": "ngram-map-k4v 最少命中次数（默认 1）。",

	// ── 📥 模型来源新增 ─────────────────────────────────────
	"lora":                    "加载 LoRA 适配器文件路径。可叠加多个。",
	"control_vector_scaled":   "带缩放的控制向量，格式 `FNAME:SCALE,...`（逗号分隔多个）。与 --control-vector-layer-range 搭配可控制影响层。",
	"lora_init_without_apply": "仅加载 LoRA 到内存但不立即应用（稍后通过 API 应用）。",
	"override_tensor":         "覆盖张量缓冲类型，格式 `张量名=缓冲类型,...`。高级调优。",
	"override_kv":             "覆盖模型元数据 KV，格式 `键=类型:值,...`。高级调优。",
	"models_dir":              "多模型路由器：模型目录（启用后单进程可切换多个模型）。",
	"models_preset":           "多模型路由器：预设 INI 文件（定义各模型参数）。",
	"models_max":              "多模型路由器：同时加载的最大模型数（默认 4）。",
	"models_autoload":         "多模型路由器：自动加载模型（默认启用）。",

	// ── 🌐 网络新增 ─────────────────────────────────────────
	"metrics":            "启用 Prometheus 兼容指标端点（/metrics），供监控采集。",
	"props":              "允许通过 POST /props 运行时修改全局参数（无需重启）。",
	"sse_ping_interval":  "SSE 流式响应的心跳间隔秒数（默认 30），防止连接被中间层断开。",
	"api_prefix":         "API 路径前缀（如填 /api 则接口变为 /api/v1/chat/completions）。",
	"reuse_port":         "允许多个 socket 绑定同一端口（配合负载均衡）。",
	"cors_headers":       "CORS 允许的请求头列表（默认 *）。",
	"cors_credentials":   "CORS 响应携带凭据（Access-Control-Allow-Credentials）。",
	"no_webui":           "禁用内置 Web UI（只留 API）。",
	"ui_config":          "JSON 形式的默认 UI 设置（覆盖 UI 默认值）。如 {\"dark_mode\":true}。",
	"slots":              "暴露 /slots 槽位监控端点（默认关）。配合 llama-commander 监控面板可查看各槽位上下文占用。",
	"path":               "静态文件服务目录（--path 指定）。",
	"media_path":         "本地媒体文件目录（供 file:// 引用图片/音频）。",
	"alias":              "模型别名（API 中 models 列表显示的名字）。",
	"tags":               "模型标签（API 元信息，逗号分隔）。",
	"tools":              "启用内置 agent 工具（read_file/grep/搜索/shell 等，逗号分隔，all=全部）。",
	"tools_runtime":      "工具运行沙箱环境：留空=本机；docker:<镜像> / podman:<镜像>=新建容器隔离；docker-container:<id> / podman-container:<id>=复用已有容器；ssh:<目标>=远程执行（需密钥+受信主机）。安全隔离用。",
	"agent":              "Agent 模式：开启 CORS 代理 + 全部内置工具，把服务变 agent 服务器。",
	"mcp_servers_config": "接入外部 MCP 服务器：指向 Cursor 格式的 JSON 配置文件。",
	"mcp_servers_json":   "接入外部 MCP 服务器：内联 JSON 定义（与 mcp-servers-config 二选一）。",
	"ui_mcp_proxy":       "为 MCP 请求提供 CORS 代理（配合前端工具调用）。",
	"rpc":                "RPC 设备列表（host:port，逗号分隔），把部分层卸载到远端 GPU 做分布式推理。",

	// ── 🧩 模板新增 ─────────────────────────────────────────
	"chat_template_kwargs":     "对话模板额外 JSON 参数（传给 Jinja 模板渲染）。",
	"skip_chat_parsing":        "跳过对话内容解析（不拆工具/推理标签，纯文本回显）。",
	"prefill_assistant":        "当末条消息是 assistant 时预填充（对续写/推理引导有用）。",
	"reasoning_preserve":       "全程保留推理轨迹（不因截断/轮次而丢失思考内容）。",
	"reasoning_budget_message": "推理预算耗尽时注入到输出的提示消息。",

	// ── 📝 日志新增 ─────────────────────────────────────────
	"reverse_prompt":     "反向提示词：生成到该内容时结束/切换（多轮交互）。",
	"special":            "输出特殊 token（如 <s>、</s>）。调试分词用。",
	"warmup":             "启动预热：加载后先跑一次小推理以初始化（默认启用）。",
	"spm_infill":         "SPM（SentencePiece）填充模式，用于代码补全。",
	"sleep_idle_seconds": "空闲 N 秒后休眠（-1=禁用）。省电场景用。",
	"log_prompts_dir":    "把每个请求的 prompt 写入该目录（调试/审计）。",
}
